// See https://github.com/pqrs-org/Karabiner-Elements/blob/main/src/apps/SettingsWindow/Resources/simple_modifications.json

export let pointingButtons = [
  'button1',
  'button2',
  'button3',
  'button4',
  'button5',
  'button6',
  'button7',
  'button8',
  'button9',
  'button10',
  'button11',
  'button12',
  'button13',
  'button14',
  'button15',
  'button16',
  'button17',
  'button18',
  'button19',
  'button20',
  'button21',
  'button22',
  'button23',
  'button24',
  'button25',
  'button26',
  'button27',
  'button28',
  'button29',
  'button30',
  'button31',
  'button32',
] as const

export type PointingButton = (typeof pointingButtons)[number]
